version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3031:3031"
    env_file:
      - .env
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telega
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./apps/telega-interface
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3031/api

  redis:
    image: redis:7
    container_name: telega_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: telega_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  pgadmin:
    image: dpage/pgadmin4
    container_name: telega_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@telega.io
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
  redis_data:
  rabbitmq_data: