apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tele-ga.fullname" . }}-secrets
  labels:
    {{- include "tele-ga.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.gateway.env.JWT_SECRET | b64enc | quote }}
  jwt-refresh-secret: {{ .Values.gateway.env.JWT_REFRESH_SECRET | b64enc | quote }}
  telegram-bot-token: {{ .Values.gateway.env.TELEGRAM_BOT_TOKEN | b64enc | quote }}
  stripe-secret-key: {{ .Values.paymentService.env.STRIPE_SECRET_KEY | b64enc | quote }}
  paypal-client-id: {{ .Values.paymentService.env.PAYPAL_CLIENT_ID | b64enc | quote }}
  paypal-client-secret: {{ .Values.paymentService.env.PAYPAL_CLIENT_SECRET | b64enc | quote }}
  database-url: {{ .Values.gateway.env.DATABASE_URL | b64enc | quote }}
  redis-url: {{ .Values.gateway.env.REDIS_URL | b64enc | quote }} 