apiVersion: v1
kind: Secret
metadata:
  name: telega-secrets
  namespace: telega
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  TELEGRAM_BOT_TOKEN: eW91cl9ib3RfdG9rZW5faGVyZQ==
  JWT_SECRET: OCpNNnQzJUBeUGY2ZEJ2NnxNU0lVXz1FaDo8Ol4/Y1ZYNnBeNHdWNGQxREpsR1dANHBWdU08aUMzYXJHN2U/Xg==
  JWT_REFRESH_SECRET: c15oW0dTPT02SCRwZSZ8KnJFSUhxe2hbM2czRzk3IV5ndVRbPls8bFMmKCFOITQyLlchZzJZLV40YkVXanBnSQ==
  DATABASE_URL: cG9zdGdyZXNxbDovL3RlbGVnYV91c2VyOnN1cGVyc2VjdXJlcGFzc3dvcmRAcG9zdGdyZXM6NTQzMi90ZWxlZ2FfZGI=
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
  MINIO_SECRET_KEY: bWluaW9hZG1pbg==
  STRIPE_SECRET_KEY: c2tfdGVzdF95b3VyX3N0cmlwZV9zZWNyZXRfa2V5X2hlcmU=
  PAYPAL_CLIENT_ID: eW91cl9wYXlwYWxfY2xpZW50X2lkX2hlcmU=
  PAYPAL_CLIENT_SECRET: eW91cl9wYXlwYWxfY2xpZW50X3NlY3JldF9oZXJl
  OPENAI_API_KEY: eW91cl9vcGVuYWlfYXBpX2tleV9oZXJl
  POSTGRES_PASSWORD: c3VwZXJzZWN1cmVwYXNzd29yZA==
  GRAFANA_PASSWORD: Z3JhZmFuYV9wYXNzd29yZA==
