name: 🧼 Clean Unused React Imports

on:
  push:
    branches:
      - main

jobs:
  clean-react:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧹 Run clean:react script
        run: npm run clean:react

      - name: 🚀 Commit changes (if any)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "🤖 Auto-remove unused 'import React'"
          git diff --cached --quiet || git push

      - name: 📢 Notify Telegram if commit happened
        if: success()
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          if [[ "$LAST_COMMIT_MSG" == *"Auto-remove unused"* ]]; then
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_DEPLOY_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_DEPLOY_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="✅ *Auto-Cleanup выполнен!*
Удалён неиспользуемый \`import React\` и отправлен коммит:
\`$LAST_COMMIT_MSG\`

[Перейти в коммит](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
          fi 