name: 🛠 Deploy with Telegram Notifications

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v3

      - name: 🚀 Run deploy
        run: |
          echo "✅ Процесс деплоя успешно выполнен."

      - name: ✅ Telegram success message
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_DEPLOY_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_DEPLOY_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="✅ *Успешный деплой!*\nПроект: *Tele•Ga*\nВетка: \`main\`\nGitHub Actions прошли успешно."

      - name: ❌ Telegram fail message
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_DEPLOY_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_DEPLOY_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="❌ *Ошибка при деплое!*\nВетка: \`main\`\nПроверь GitHub Actions логи." 