name: Deploy with Telegram Notification

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: ⚙️ Build & Deploy
        run: |
          echo "🔧 Здесь будет деплой..."
          # ./deploy.sh или любая другая команда деплоя

      - name: ✅ Send success Telegram notification
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_DEPLOY_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_DEPLOY_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="✅ *Успешный деплой проекта Tele•Ga!*\nВетка: \`main\`\n✅ Всё прошло успешно."

      - name: ❌ Send failure Telegram notification
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_DEPLOY_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_DEPLOY_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="❌ *Ошибка деплоя проекта Tele•Ga!*\nВетка: \`main\`\nПроверьте логи GitHub Actions." 